### ISSUE TITLE
not working on ubuntu 18.04

### ISSUE THREAD

**Issue by besingamkb** [TimeTraveller-San/yTermPlayer#10]
Hi after installing the requirements because I only have python 2.7. `yterm` command is not working on my end. I got this error.
```
$ yterm
Traceback (most recent call last):
  File "/home/mark/.local/bin/yterm", line 6, in <module>
    from yTermPlayer.__main__ import main
  File "/home/mark/.local/lib/python3.6/site-packages/yTermPlayer/__main__.py", line 11, in <module>
    from .music_api import YoutubePlayer
  File "/home/mark/.local/lib/python3.6/site-packages/yTermPlayer/music_api.py", line 11, in <module>
    import mpv
  File "/home/mark/.local/lib/python3.6/site-packages/mpv.py", line 42, in <module>
    raise OSError("Cannot find libmpv in the usual places. Depending on your distro, you may try installing an "
OSError: Cannot find libmpv in the usual places. Depending on your distro, you may try installing an mpv-devel or mpv-libs package. If you have libmpv around but this script can't find it, maybe consult the documentation for ctypes.util.find_library which this script uses to look up the library filename.
```

**Comment by 4shadoww** [comment]
Have you installed libmpv? Package `libmpv-dev` should provide it on ubuntu.

**Comment by vaibkumr** [comment]
[python mpv](https://github.com/jaseg/python-mpv) is only a wrapper around [libmpv](https://packages.ubuntu.com/search?keywords=libmpv-dev) for ubuntu
also, this does not support python 2.7
