### ISSUE TITLE
No module named 'mpv'

### ISSUE THREAD

**Issue by jamcmich** [TimeTraveller-San/yTermPlayer#18]
Hi there,

I'm fairly new to Python so this could be a user error. After setting up a venv and installing the necessary dependencies for your application for Python3 via pip, I get this error when running the 'yterm' command:

```
Traceback (most recent call last):
  File "c:\users\jamcmich\appdata\local\programs\python\python38-32\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\jamcmich\appdata\local\programs\python\python38-32\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\jamcmich\AppData\Local\Programs\Python\Python38-32\Scripts\yterm.exe\__main__.py", line 5, in <module>
  File "c:\users\jamcmich\appdata\local\programs\python\python38-32\lib\site-packages\yTermPlayer\__main__.py", line 11, in <module>
    from .music_api import YoutubePlayer
  File "c:\users\jamcmich\appdata\local\programs\python\python38-32\lib\site-packages\yTermPlayer\music_api.py", line 11, in <module>
    import mpv
ModuleNotFoundError: No module named 'mpv'
```

How can I resolve this?

**Comment by vaibkumr** [comment]
Hi,
This error is because of not properly installing `python-mpv==0.3.9`. Have you tried activating the virtual env and then install the dependencies? Maybe, do a `pip install --user python-mpv==0.3.9`. If this doesn't work, you might have to configure your python environment $PATH.
You also need to install the mpv package on your operating system.

EDIT2: I just noticed you're trying to run this on windows. I am sorry, ytermplayer isn't supported for windows yet. I will soon make a port to windows.
