### ISSUE TITLE
Can't play live stream video

### ISSUE THREAD

**Issue by froggologies** [TimeTraveller-San/yTermPlayer#22]
Traceback (most recent call last):
  File "/usr/bin/yterm", line 8, in <module>
    details = self.get_url_and_name(index)
  File "/home/frog/.local/lib/python3.9/site-packages/yTermPlayer/music_api.py", line 159, in get_url_and_name
    self.playlist['items'][int(index)]['pafy'].getbestaudio().url,
    sys.exit(main())
ValueError: cannot convert float NaN to integer

During handling of the above exception, another exception occurred:

  File "/home/frog/.local/lib/python3.9/site-packages/yTermPlayer/__main__.py", line 28, in main
Traceback (most recent call last):
  File "/home/frog/.local/lib/python3.9/site-packages/yTermPlayer/music_api.py", line 225, in play_at_index
    loop.run()
  File "/home/frog/.local/lib/python3.9/site-packages/urwid/main_loop.py", line 286, in run
    details = self.get_url_and_name(index)
  File "/home/frog/.local/lib/python3.9/site-packages/yTermPlayer/music_api.py", line 159, in get_url_and_name
    self.playlist['items'][int(index)]['pafy'].getbestaudio().url,
    self._run()
ValueError: cannot convert float NaN to integer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/frog/.local/lib/python3.9/site-packages/urwid/main_loop.py", line 384, in _run
  File "/home/frog/.local/lib/python3.9/site-packages/yTermPlayer/music_api.py", line 225, in play_at_index
    details = self.get_url_and_name(index)
  File "/home/frog/.local/lib/python3.9/site-packages/yTermPlayer/music_api.py", line 159, in get_url_and_name
    self.event_loop.run()
  File "/home/frog/.local/lib/python3.9/site-packages/urwid/main_loop.py", line 788, in run
    self.playlist['items'][int(index)]['pafy'].getbestaudio().url,
ValueError: cannot convert float NaN to integer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/frog/.local/lib/python3.9/site-packages/yTermPlayer/music_api.py", line 225, in play_at_index
    self._loop()
  File "/home/frog/.local/lib/python3.9/site-packages/urwid/main_loop.py", line 821, in _loop
    details = self.get_url_and_name(index)
  File "/home/frog/.local/lib/python3.9/site-packages/yTermPlayer/music_api.py", line 159, in get_url_and_name
    alarm_callback()
  File "/home/frog/.local/lib/python3.9/site-packages/urwid/main_loop.py", line 172, in cb
    self.playlist['items'][int(index)]['pafy'].getbestaudio().url,
ValueError: cannot convert float NaN to integer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/frog/.local/lib/python3.9/site-packages/yTermPlayer/music_api.py", line 225, in play_at_index
    callback(self, user_data)
  File "/home/frog/.local/lib/python3.9/site-packages/yTermPlayer/ui.py", line 87, in update_name
    details = self.get_url_and_name(index)
  File "/home/frog/.local/lib/python3.9/site-packages/yTermPlayer/music_api.py", line 159, in get_url_and_name
    self.list[int(self.player_object.get_index())].set_attr_map({
ValueError: cannot convert float NaN to integer

**Comment by vaibkumr** [comment]
This project is only capable of streaming youtube playlists. Livestreams are not supported. Please see larger projects like [mps-youtube](https://github.com/mps-youtube/mps-youtube) for more features.
