### ISSUE TITLE
Player crashes once I copy the URL and press OK with the error "IndexError: tuple index out of range"

### ISSUE THREAD

**Issue by 6lackb1rd** [TimeTraveller-San/yTermPlayer#24]
Please help me load playlists into the player. Currently it just outputs the  following message in the terminal:
`During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ishmam/.local/bin/yterm", line 8, in <module>
    sys.exit(main())
  File "/home/ishmam/.local/lib/python3.8/site-packages/yTermPlayer/__main__.py", line 28, in main
    loop.run()
  File "/home/ishmam/.local/lib/python3.8/site-packages/urwid/main_loop.py", line 287, in run
    self._run()
  File "/home/ishmam/.local/lib/python3.8/site-packages/urwid/main_loop.py", line 385, in _run
    self.event_loop.run()
  File "/home/ishmam/.local/lib/python3.8/site-packages/urwid/main_loop.py", line 792, in run
    if e.args[0] != 4:
IndexError: tuple index out of range
`

I am a newbie at python and cannot to figure out the problem. Please help.

**Comment by burton11** [comment]
I have the same problem, and i keep all my packages upgraded constantly.
Solution would be really appreciated

**Comment by b33lz3bubTH** [comment]
this isnt maintained, anymore i guess.

**Comment by Jirido** [comment]
Same here. :(

**Comment by pataquets** [comment]
Experiencing the same, everyone else encouraged to add your :+1: to the issue description.
@vaibkumr: pinging you in case you're not getting notifications. Also, if you're unable to maintain the project, consider opening the project for co-maintainership or adoption (https://adoptoposs.org might come handy), since the project is very useful. Creating issue and/or posting in the readme would help. In any case, thanks for sharing!
