### ISSUE TITLE
error on startup

### ISSUE THREAD

**Issue by kocierik** [TimeTraveller-San/yTermPlayer#25]
<code>
> yterm
Traceback (most recent call last):
  File "/usr/local/bin/yterm", line 33, in <module>
    sys.exit(load_entry_point('yTermPlayer==1.2.1', 'console_scripts', 'yterm')())
  File "/usr/local/bin/yterm", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/local/Cellar/python@3.9/3.9.1_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/local/Cellar/python@3.9/3.9.1_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/local/lib/python3.9/site-packages/yTermPlayer/__main__.py", line 11, in <module>
    from .music_api import YoutubePlayer
  File "/usr/local/lib/python3.9/site-packages/yTermPlayer/music_api.py", line 11, in <module>
    import mpv
  File "/usr/local/lib/python3.9/site-packages/mpv.py", line 42, in <module>
    raise OSError("Cannot find libmpv in the usual places. Depending on your distro, you may try installing an "
OSError: Cannot find libmpv in the usual places. Depending on your distro, you may try installing an mpv-devel or mpv-libs package. If you have libmpv around but this script can't find it, maybe consult the documentation for ctypes.util.find_library which this script uses to look up the library filename.
</code>

I tried to reinstall mpv

**Comment by hiran-sarkar** [comment]
@kocierik  You need to have libmpv installed
