### ISSUE TITLE
Error on startup.

### ISSUE THREAD

**Issue by MikeCase** [TimeTraveller-San/yTermPlayer#28]
Using python 3.10 in a fresh virtualenv. However, I have installed it without a virtualenv in with python 3.8 and received roughly the same error I'm not sure if this is a problem with the version of mpv/libmpv I have installed on my system or if it's an issue with python-mpv. OR if it's just a minor bug in ytermplayer. 

## Linux distro/version
No LSB modules are available.
Distributor ID:	Linuxmint
Description:	Linux Mint 20.3
Release:	20.3
Codename:	una

## Software Versions
mpv: 0.32.0 
libmpv: 0.32.0
python-mpv: 1.0.1
python: 3.8 | 3.10
venv | no venv

## The traceback

`Traceback (most recent call last):
  File "/home/splaq/.config/venv/py310testing/bin/yterm", line 5, in <module>
    from yTermPlayer.__main__ import main
  File "/home/splaq/.config/venv/py310testing/lib/python3.10/site-packages/yTermPlayer/__main__.py", line 11, in <module>
    from .music_api import YoutubePlayer
  File "/home/splaq/.config/venv/py310testing/lib/python3.10/site-packages/yTermPlayer/music_api.py", line 11, in <module>
    import mpv
  File "/home/splaq/.config/venv/py310testing/lib/python3.10/site-packages/mpv.py", line 579, in <module>
    _handle_func('mpv_event_to_node',           [POINTER(MpvNode), POINTER(MpvEvent)],      c_int, ec_errcheck, ctx=None)
  File "/home/splaq/.config/venv/py310testing/lib/python3.10/site-packages/mpv.py", line 502, in _handle_func
    func = getattr(backend, name)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 387, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 392, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /lib/x86_64-linux-gnu/libmpv.so.1: undefined symbol: mpv_event_to_node. Did you mean: 'mpv_event_name'?`
'

**Comment by MikeCase** [comment]
So upon further review of the issue, I just commented that line out in the mpv.py (line #579) file and it loaded. Haven't tested the application beyond that however. I do realize this isn't the correct fix for the issue, but it seems to have worked for at least a simple workaround for the time being.
