### ISSUE TITLE
ModuleNotFoundError: No module named 'vlc'

### ISSUE THREAD

**Issue by vaibkumr** [TimeTraveller-San/yTermPlayer#3]
Traceback (most recent call last):
  File "/home/timetraveller/miniconda3/bin/yterm", line 7, in <module>
    from yTermPlayer.__main__ import main
  File "/home/timetraveller/miniconda3/lib/python3.6/site-packages/yTermPlayer/__init__.py", line 2, in <module>
    import vlc
ModuleNotFoundError: No module named 'vlc'

**Comment by vaibkumr** [comment]
Fixed it in version 1.2.1
vlc is no more needed. It was there by mistake.
