### ISSUE TITLE
Can't run it

### ISSUE THREAD

**Issue by blacklightpy** [TimeTraveller-San/yTermPlayer#4]
Trying pip method:

```
C:\Users\Blacklight>yterm
Traceback (most recent call last):
  File "c:\program files (x86)\python37-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files (x86)\python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Blacklight\AppData\Roaming\Python\Python37\Scripts\yterm.exe\__main__.py", line 5, in <module>
  File "C:\Users\Blacklight\AppData\Roaming\Python\Python37\site-packages\yTermPlayer\__main__.py", line 11, in <module>
    from .music_api import YoutubePlayer
  File "C:\Users\Blacklight\AppData\Roaming\Python\Python37\site-packages\yTermPlayer\music_api.py", line 11, in <module>
    import mpv
  File "C:\Users\Blacklight\AppData\Roaming\Python\Python37\site-packages\mpv.py", line 31, in <module>
    backend = CDLL('mpv-1.dll')
  File "c:\program files (x86)\python37-32\lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found
```

Trying clone method:

```
D:\Projects\yTermPlayer\yTermPlayer>python __main__.py
Traceback (most recent call last):
  File "__main__.py", line 11, in <module>
    from .music_api import YoutubePlayer
ModuleNotFoundError: No module named '__main__.music_api'; '__main__' is not a package
```

**Comment by vaibkumr** [comment]
I see you're trying to run this on windows. Currently, it has no support for windows because of some dependencies. I will release a version for windows soon though. 
Also, to use the clone method following changes need to be done: https://github.com/TimeTraveller-San/yTermPlayer/issues/2 (I will fix it as soon as I get time). Again, even the cloned version will only work on linux and not windows.
